version: '3.1'

services:
  car_driver:
    image: public.ecr.aws/paia-tech/pros-car:latest
    env_file:
      - .env
    environment:
      - ROS_DOMAIN_ID
      - SERIAL_DEV_DEFAULT
    network_mode: host
    privileged: true
    # TODO connect the device you need
    command: ros2 launch pros_car_py carA_driver.launch.py
  
  carA_random:
    image: public.ecr.aws/paia-tech/pros-car:latest
    env_file:
      - .env
    environment:
      - ROS_DOMAIN_ID
    network_mode: host

    command: ros2 launch pros_car_py carA_random.launch.py

  # rosbridge:
  # random:
